package clinica;

import datos.Paciente;
import datos.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author keiinerp
 */
public class Login extends javax.swing.JDialog {

    /**
     * Creates new form Login
     */
    ArrayList<Usuario> usuariosRegistrados;
    RegistrarUsuario registrarUsuarioVentana;
    ArrayList<Paciente> listaPacientes;
    Usuario usuario;

    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        registro = 0;
        usuariosRegistrados = Archivo.leerUsuarioBinario();
        listaPacientes = Archivo.leerPacientesBinario();
        if (usuariosRegistrados == null) {
            usuario = new Usuario();
            usuario.setClave("123");
            usuario.setNombre("Kevin");
            usuario.setEdad(19);
            usuario.setIdentificacion("1193222");
            usuario.setTipo("ADMINISTRADOR");
            usuario.setUsuario("admin");
            Archivo.escribirListaUsuarios(usuariosRegistrados);
            usuariosRegistrados.add(usuario);
            Archivo.escribirListaUsuarios(usuariosRegistrados);
        }
        listaPacientes = Archivo.leerPacientesBinario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserText = new javax.swing.JTextField();
        entrarBoton = new javax.swing.JButton();
        registrarBoton = new javax.swing.JButton();
        claveText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso de usuario");

        registroTitulo.setText("No tienes un usuario Regístrate");
        registroTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroTituloMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido a la Clínica Valledupar");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        entrarBoton.setText("Entrar");
        entrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBotonActionPerformed(evt);
            }
        });

        registrarBoton.setText("Registrar");
        registrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBotonActionPerformed(evt);
            }
        });

        claveText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registroTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(registrarBoton)
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserText, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(claveText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entrarBoton)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(claveText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(entrarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroTitulo)
                    .addComponent(registrarBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroTituloMouseClicked

    }//GEN-LAST:event_registroTituloMouseClicked

    private void entrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotonActionPerformed
        int i = 0;
        String user;
        String password;
        int correcto = 0;
        user = UserText.getText();
        password = claveText.getText();
        try {
            for (Usuario listaUsuario : usuariosRegistrados) {
                if (listaUsuario.getClave().equals(password) && listaUsuario.getUsuario().equals(user)) {
                    usuario = usuariosRegistrados.get(i);
                    dispose();
                    Principal principalVentana = new Principal();
                    principalVentana.setVisible(true);
                    correcto = 1;
                } else {
                    correcto = 0;
                }
                if (correcto == 1) {
                    break;
                }
            }
            if (correcto == 0) {
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor registre un usuario");

        }

    }//GEN-LAST:event_entrarBotonActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(null, true).setVisible(true);
            }
        });
    }

    /*
       for (int i = 0; i < listaUsuarios.size(); i++){
        if(listaUsuarios.get(i).getUsuario().equals(user) && listaUsuarios.get(i).getClave().equals(password)){
            JOptionPane.showMessageDialog(null, "BIENVENIDO");
            Principal principalVentana = new Principal();
            principalVentana.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"USUARIO y/o CONTRASEÑA INCORRECTOS");
        }
        }
     */
    private void registrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBotonActionPerformed
        String pass = JOptionPane.showInputDialog(this, "Ingrese el codigo administrativo");
        if (pass.equals("1141")) {
            registrarUsuarioVentana = new RegistrarUsuario(null, true);
            registrarUsuarioVentana.setVisible(true);
            registro = RegistrarUsuario.registro;
            editado = RegistrarUsuario.editado;
            eliminado = RegistrarUsuario.eliminado;
            if (registro == 1 || eliminado == 1 || editado == 1) {
                usuariosRegistrados = Archivo.leerUsuarioBinario();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pase incorrecto, por favor verifique");
        }

    }//GEN-LAST:event_registrarBotonActionPerformed

    private void claveTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UserText;
    private javax.swing.JPasswordField claveText;
    private javax.swing.JButton entrarBoton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton registrarBoton;
    private javax.swing.JLabel registroTitulo;
    // End of variables declaration//GEN-END:variables
public static int registro = 0, editado = 0, eliminado = 0;
}
